name: Test 1

# KIEDY MA SIĘ URUCHOMIĆ:
on:
  push:              # <-- To sprawi, że ruszy sam po wrzuceniu plików!
  workflow_dispatch: # To zostawiamy dla przycisku na przyszłość

jobs:
  odpalanie-exe:
    runs-on: windows-latest

    steps:
      - name: Pobierz pliki z repozytorium
        uses: actions/checkout@v5

      
